### ISSUE TITLE
Compile error: "Reference to member 'value' cannot be resolved without a contextual type"

### ISSUE THREAD

**Issue by broadwaylamb** [mczachurski/Swiftgger#1]
The library cannot be compiled with Swift 4.1 because of the error in [`OpenAPIExample.swift`, line 47](https://github.com/mczachurski/Swiftgger/blob/master/Sources/Swiftgger/OpenAPIModel/OpenAPIExample.swift#L47):

```swift
try container.encode(value, forKey: .value) // ERROR: Reference to member 'value' cannot be resolved without a contextual type
```

That's because the `value` property is of type `Optional<Any>`. Prior to Swift 4.1 `Optional` conformed to the `Encodable` protocol unconditionally at compile time, but attempting to encode its payload if the payload is not itself `Encodable` **would crash at runtime**.

Swift 4.1 introduced conditional conformances, and now this error is caught at compile time, which results in the inability to compile Swiftgger.

My suggestion would be to make the `OpenAPIExample` class generic:

```diff
-public class OpenAPIExample: Encodable
+public class OpenAPIExample<Value: Encodable>: Encodable {

     public private(set) var ref: String?
     public private(set) var summary: String?
     public private(set) var description: String?
-    public private(set) var value: Any?
+    public private(set) var value: Value?
     public private(set) var externalValue: String?
```
However, I haven't tried this and not sure if it'll work with the rest of the project.

I'm looking forward to be able to use Swiftgger in my Vapor project 😊

**Comment by mczachurski** [comment]
Fixed in commit db3140b2183f7b80f15e3d53ee3046769950aab7. 

It's not perfect solution, however now Swiftgger didn't provide API to set up examples objects in OpenAPI JSON.
