### ISSUE TITLE
Authorization header

### ISSUE THREAD

**Issue by PanArtemG** [mczachurski/Swiftgger#14]
Hi! I need help from Authorization header, please.

My APIParameter - 
APIParameter(name: "Authorization", parameterLocation: .header, description: "Bearer xxxxxx", required: true, dataType: .string)

I do not understand whether I'm doing everything? But I can't get access using real Token

Thanks in advance!

**Comment by mczachurski** [comment]
Hi,

If you want to use JWT Authorization you need to specify `authorizations` parameter in `OpenAPIBuilder`, for example:

```swift
let openAPIBuilder = OpenAPIBuilder(
    title: "Tasker server API",
    version: "1.0.0",
    description: "This is a sample server for task server application.",
    termsOfService: "http://example.com/terms/",
    contact: APIContact(name: "John Doe", email: "john.doe@some-email.org", url: URL(string: "http://example-domain.com/@john")),
    license: APILicense(name: "MIT", url: URL(string: "http://mit.license")),
    authorizations: [.jwt(description: "You can get token from *sign-in* action from *Account* controller.")]
)
```

Then you have in Swagger client button "Authorize" where you can set Bearer token, and that token Swagger will automatically sent with all requests.

**Comment by PanArtemG** [comment]
I added authorizations: [ .jwt ] and all worked! Thank you :)
