### ISSUE TITLE
Place OpenAPI on my server

### ISSUE THREAD

**Issue by PanArtemG** [mczachurski/Swiftgger#15]
Hello!)
Friend, please tell me. Taskerswift-swagger is currently hosted at azurewebsites.net. - https://taskerswift-swagger.azurewebsites.net/

How can I host it on my server?
Example - https://taskerswift-swagger.my-server.net/
Is it possible?

**Comment by eneko** [comment]
Hi @PanArtemG,

You can use Swiftgger to generate an Open API 3.0 spec for your API. Using Swift, you can write code to define the API endpoints, data transfer objects, authorization, etc. This spec, is usually serialized to JSON using `JSONEncoder`.

Meanwhile, what you see on Taskerswift-swagger, is [SwaggerUI](https://github.com/swagger-api/swagger-ui), which you can download and set up in your web server. Depending on which technology stack your web-server utilizes, you might find packages or libraries that include SwaggerUI.

Hope that helps!
Eneko

**Comment by PanArtemG** [comment]
Hello!
Thanks for the answer, but it doesn't match what I was asking. This is a great library and I have already implemented OpenAPI for my server.
But I want to deploy Taskerswift-swagger for example on "Heroku" (https://www.heroku.com/), how can I do this?

**Comment by PanArtemG** [comment]
Example - https://taskerswift-swagger.heroku.net/

**Comment by eneko** [comment]
@mczachurski correct me if I'm wrong, but Taskerbwift-swagger is not a real service, but just a demo spec, similar to the Pet Store at https://petstore.swagger.io

@PanArtemG are you asking about how to deploy SwaggerUI to Heroku? What you see on https://taskerswift-swagger.azurewebsites.net is just SwaggerUI, nothing else.

**Comment by mczachurski** [comment]
For host your Open API definition (which you can build with Swiftgger) you have a few choices. You can use virtual machine (e.g. Linux) in some hosting providers or use Docker images. Almost all big hosting providers supports Docker. Also that site: [https://taskerswift.azurewebsites.net/openapi](https://taskerswift.azurewebsites.net/openapi) is hosted in Azure as a Docker image. This is link to the image in Docker Hub: [https://hub.docker.com/r/mczachurski/taskerserverswift](https://hub.docker.com/r/mczachurski/taskerserverswift). Open API definition (Swiftgger) should be built in your real application. You have then all entities (models) which your API serve.

However you have to remember that Swiftgger exposes only Open API definition (JSON). Thus you have to also use static [SwaggerUI](https://github.com/swagger-api/swagger-ui) page and host it somewhere (you have to set only URL to Open API definition).

That site: [https://taskerswift-swagger.azurewebsites.net/](https://github.com/swagger-api/swagger-ui) is a static page hosted in Azure with link to (previously described) Docker image.

**Comment by PanArtemG** [comment]
Thanks! It seems that this is what I need! I still have one last question, but I will ask it in a separate topic.
