### ISSUE TITLE
Classes and Struct to APIObject 

### ISSUE THREAD

**Issue by PanArtemG** [mczachurski/Swiftgger#16]
Hello again!)
I hope this is my last question))

When I initialize the Struct and add it as APIObject (object: userResponse)
The description in the description of the circuit is all displayed perfectly!

It is - struct UserResponse
![Снимок экрана 2020-11-27 в 11 17 08](https://user-images.githubusercontent.com/52529151/100432314-1cbe4980-30a2-11eb-8764-c502fc0febad.png)

But when I do the same with the class I get a completely different result.
It is - final class User
![Снимок экрана 2020-11-27 в 11 18 05](https://user-images.githubusercontent.com/52529151/100432399-3c557200-30a2-11eb-8bb8-9348dae5d011.png)

What am I doing wrong?

**Comment by mczachurski** [comment]
Hi, I cannot reproduce the issue. Could you share class definition?

**Comment by PanArtemG** [comment]
`import Fluent
import Vapor


/// A generic `User` data.
final class User: Model, Content {
    
    /// Name of the table or collection.
    static let schema = "users"
    
    /// Unique identifier for this `User`
    @ID(key: .id)
    var id: UUID?
    
    /// The `User` first name
    @Field(key: "first_name")
    var firstName: String
    
    /// The `User` last name
    @Field(key: "last_name")
    var lastName: String
    
    /// The `User` middle name
    @Field(key: "middle_name")
    var middleName: String?
    
    /// The `User` avatar
    @Field(key: "avatar")
    var avatar: Media?
    
    /// The identificator of `GoogleUser` that owner
    @Field(key: "google_user_id")
    var googleUserID: String?
    
    /// The `GoogleUserInfo` of a children relation.
    @Children(for: \.$user)
    var googleUserInfo: [GoogleUserInfo]
    
    /// The identificator of `FacebookUser` that owner
    @Field(key: "facebook_user_id")
    var facebookUserID: String?
    
    /// The `FacebookUserInfo` of a children relation.
    @Children(for: \.$user)
    var facebookUserInfo: [FacebookUserInfo]
    
    /// The identificator of `AppleUser` that owner
    @Field(key: "apple_user_id")
    var appleUserID: String?

    /// The `AppleUserInfo` of a children relation.
    @Children(for: \.$user)
    var appleUserInfo: [AppleUserInfo]
    
    /// The `User` email
    @Field(key: "email")
    var email: String?
    
    /// The `User` phone number
    @Field(key: "phone_number")
    var phoneNumber: String?
    
    /// The `User` password hash
    @Field(key: "password_hash")
    var passwordHash: String
    
    /// The property that indicates whether the `Email` is a Verified
    @Field(key: "is_email_verified")
    var isEmailVerified: Bool
    
    /// The property that indicates whether the `PhoneNumber` is a Verified
    @Field(key: "is_phone_number_verified")
    var isPhoneNumberVerified: Bool
    
    /// Stores type of `GenderType` as a native database enum
    @Enum(key: "gender")
    var gender: GenderType
    
    /// The `User` birthDate
    @Field(key: "birth_date")
    var birthDate: Date?
    
    /// Stores type of `UserType` as a native database enum
    @Enum(key: "type")
    var userType: UserType
    
    /// The `Address` of a children relation.
    @Children(for: \.$user)
    var addresses: [Address]
    
    /// When this `User` was created.
    @Timestamp(key: "created_at", on: .create)
    var createdAt: Date?
    
    /// When this `User` was last updated.
    @Timestamp(key: "updated_at", on: .update)
    var updatedAt: Date?
    
    /// When this `User` was deleted.
    @Timestamp(key: "deleted_at", on: .delete)
    var deletedAt: Date?
    `

**Comment by eneko** [comment]
Interesting issue. Property wrappers really affect the structure of objects. As their name indicates, they "wrap" the property inside a separate structure/class. 

@mczachurski I think it should be possible to detect the wrappers and surface the enclosed data type, but haven't done that before, so not sure.

**Comment by mczachurski** [comment]
Yes property wrappers affects the structure of objects. For now I don't have any idea how to solve that issue. However I will try to figure out something.

**Comment by mczachurski** [comment]
I created new version of Swiftgger with some solution of the issue. I'm not sure if it's bullet proof thus I will glad to hear your feedback.
