### ISSUE TITLE
CamelCase to snake_case

### ISSUE THREAD

**Issue by gulivero1773** [mczachurski/Swiftgger#20]
Hello, how  can I convert the structure model from camelCase to snake_case model in Object - 
![Снимок экрана 2021-05-22 в 09 43 40](https://user-images.githubusercontent.com/61082418/119217334-320cb180-bae2-11eb-8f16-1b0002c8e345.png)
My response from service
![Снимок экрана 2021-05-22 в 09 44 51](https://user-images.githubusercontent.com/61082418/119217355-5e283280-bae2-11eb-83c3-d77eb8a7c543.png)

**Comment by mczachurski** [comment]
If I understood correctly, you have in your model properties in camelCase but you convert them to snake case during encoding to JSON. Unfortunately it's not possible to achieve same thing in Swiftgger right now.

**Comment by gulivero1773** [comment]
Thank you. You correctly understood my question. Are you planning to improve this functionality in the near future? @mczachurski

**Comment by mczachurski** [comment]
Hi. Yes I will implement this feature (maybe in this or next week I will find some time for that).

**Comment by mczachurski** [comment]
I'm reopening the issue since is not implemented yet.

**Comment by mczachurski** [comment]
Change has been implemented. It's much bigger, that's why I've published version 2.0.0-rc1. I would be glad if you will send me information if everything will work for you. Then I will prepare official version 2.0.0.

**Comment by gulivero1773** [comment]
It works for me. Thank you for your help.
