### ISSUE TITLE
Dictionary object

### ISSUE THREAD

**Issue by gulivero1773** [mczachurski/Swiftgger#31]
Hello, can you add 
<img width="464" alt="Снимок экрана 2021-06-25 в 12 50 31" src="https://user-images.githubusercontent.com/61082418/123406770-ee5f0900-d5b3-11eb-836b-621d002902c5.png">
Dictionary to APIResponse or how I need use dictionary in response?

**Comment by gulivero1773** [comment]
![Снимок экрана 2021-06-25 в 13 06 44](https://user-images.githubusercontent.com/61082418/123408878-341cd100-d5b6-11eb-8177-89754d20fabe.png)
Because I have this error

**Comment by mczachurski** [comment]
That feature has not been implemented. I've added support for dictionaries in response/request to version 2.0.0-rc2. 

You have to write (note that key in dictionary is always `String` and we have to specify only value type):

```swift
APIResponse(code: "200", description: "Ok", type: .dictionary(String.self))
```

Can you confirm that this is working for you now?

**Comment by gulivero1773** [comment]
Thanks for your update! It work for me.
